packages:
  - packages/*
  - scripts
  - tests
  - docs
  - content

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - tesseract.js
  - unrs-resolver
  - vue-demi
