name: Deploy to Production

on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    
    env:
      DOCKER_REGISTRY: "your-registry" # e.g., ghcr.io
      DOCKER_IMAGE_BACKEND: "testloom-backend"
      DOCKER_IMAGE_FRONTEND: "testloom-frontend"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build applications
        run: pnpm build
      
      - name: Run tests
        run: pnpm test
      
      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # registry: ${{ env.DOCKER_REGISTRY }} # Uncomment if using a different registry
      
      - name: Build and push Docker images
        run: |
          docker build -f docker/backend.Dockerfile -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BACKEND }}:${{ github.sha }} .
          docker build -f docker/frontend.Dockerfile -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_FRONTEND }}:${{ github.sha }} .
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BACKEND }}:${{ github.sha }}
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_FRONTEND }}:${{ github.sha }}
      
      - name: Deploy to production
        run: |
          echo "Deploying version ${{ github.sha }} to production..."
          # Example: kubectl set image deployment/testloom-backend backend=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BACKEND }}:${{ github.sha }}
          # Example: docker stack deploy --compose-file docker-compose.prod.yml testloom
